export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function JobsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="min-h-screen bg-background">
      {children}
    </div>
  )
}
